# Generated by Django 6.0.7 on 2026-08-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_rename_category_blog_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_heading', models.CharField(max_length=30)),
                ('about_descrition', models.TextField(max_length=255)),
            ],
        ),
    ]
